#!/usr/bin/env python3
"""
AAQC runner with FeatMaker-style regex / option / src_file handling.

Changes from original aaqc:
- Removed manual SRC_MAP; src_file is now randomly picked from the benchmark base dir
  (one fixed src_file for the entire run; diff gets two).
- Removed manual per-program build_run_args; instead:
  1) option: randomly picked from `<program> --help` output each KLEE invocation
  2) regex: randomly generated by regexgen each KLEE invocation
  3) src_file: fixed at program start (random from file pool)
  Assembled as: option regex src_file (with program-specific regex formatting).
- sed, gawk, csplit use /regex/ format.
- diff uses two src_files.
"""
import argparse
import os
import json
import sys
import subprocess as sp
import glob
import time
import shlex
import random
import string
import tempfile
import re
from _shared import get_regex_mode, compose_root  # shared table + repo root
import shutil
from pathlib import Path
from typing import Optional, List, Set, Dict


# ========================= Naive SeedCache =========================
class NaiveSeedCache:
    """Store all ktests per execution, return random seed dir."""
    def __init__(self, root: Path):
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)
        self.entries: List[str] = []

    def store(self, build_idx: int, j: int, outdir: str) -> None:
        src = Path(outdir)
        if not src.exists():
            return
        ktests = list(src.glob("*.ktest"))
        if not ktests:
            return
        seed_dir = self.root / f"b{build_idx}-j{j}"
        seed_dir.mkdir(parents=True, exist_ok=True)
        copied = 0
        for kt in ktests:
            try:
                dst = seed_dir / kt.name
                if not dst.exists():
                    shutil.copy2(str(kt), str(dst))
                    copied += 1
            except Exception:
                pass
        if copied > 0:
            self.entries.append(str(seed_dir))

    def get_random_seed_dir(self) -> Optional[str]:
        if not self.entries:
            return None
        return random.choice(self.entries)

# ----------------------- mappings / config -----------------------

test_dir = {
    'grep': 'GR',
    'sed': 'SE',
    'gawk': 'GA',
    'nano': 'NA',
    'diff': 'DI',
    'find': 'FI',
    'csplit': 'CS',
    'ptx': 'PT',
    'expr': 'EX',
    'm4': 'M4',
    'tac': 'TC',
    'nl': 'NL',
}

flags = {
    'csplit': '-max-memory=4000 -allocate-determ -allocate-determ-start-address=0x0 -allocate-determ-size=4000 -search=dfs -use-forked-solver -disable-inlining -watchdog -switch-type=internal -simplify-sym-indices',
    'ptx': '-max-memory=4000 -allocate-determ -allocate-determ-start-address=0x0 -allocate-determ-size=4000 -search=dfs -use-forked-solver -disable-inlining -watchdog -switch-type=internal -simplify-sym-indices',
    'expr': '-max-memory=4000 -allocate-determ -allocate-determ-start-address=0x0 -allocate-determ-size=4000 -search=dfs -use-forked-solver -disable-inlining -watchdog -switch-type=internal -simplify-sym-indices',
    'tac': '-max-memory=4000 -allocate-determ -allocate-determ-start-address=0x0 -allocate-determ-size=4000 -search=dfs -use-forked-solver -disable-inlining -watchdog -switch-type=internal -simplify-sym-indices',
    'nl': '-max-memory=4000 -allocate-determ -allocate-determ-start-address=0x0 -allocate-determ-size=4000 -search=dfs -use-forked-solver -disable-inlining -watchdog -switch-type=internal -simplify-sym-indices',
}

sym_commands = {
    'csplit': '-sym-args 0 1 10 -sym-args 0 2 2 -sym-files 1 8 -sym-stdin 8 -sym-stdout',
    'ptx': '-sym-args 0 1 10 -sym-args 0 2 2 -sym-files 1 8 -sym-stdin 8 -sym-stdout',
    'expr': '-sym-args 0 1 10 -sym-args 0 2 2 -sym-files 1 8 -sym-stdin 8 -sym-stdout',
    'tac': '-sym-args 0 1 10 -sym-args 0 2 2 -sym-files 1 8 -sym-stdin 8 -sym-stdout',
    'nl': '-sym-args 0 1 10 -sym-args 0 2 2 -sym-files 1 8 -sym-stdin 8 -sym-stdout',
}

# per-program default regex mode mapping

# programs needing two src_files (e.g. diff)
_DUAL_SRC_PROGRAMS = {"diff"}

# ----------------------- utility functions -----------------------
def _escape_sq(s):
    """Escape single quotes for shell."""
    return s.replace("'", "'\"'\"'")


def get_mode_for_prog(prog, cli_mode):
    """CLI mode takes precedence; else per-program default; else 'ere'."""
    if cli_mode:
        return cli_mode
    return get_regex_mode(prog, "ere")


def generate_regex_with_regexgen(mode="ere"):
    """Generate one regex via regexgen and return it as a string."""
    with tempfile.NamedTemporaryFile(mode="r+", delete=False) as tf:
        path = tf.name
    try:
        sp.run(["regexgen", "-c", "1", "-f", path], check=True)
        with open(path, "r") as f:
            for line in f:
                s = line.strip()
                if s:
                    return s
        return ""
    finally:
        try:
            os.remove(path)
        except Exception:
            pass


# ----------------------- src_file: random file pool (from featmaker) -----------------------
def _derive_src_base_dir(prog, pcfg=None):
    """Derive the source-tree base dir from pgm-config (parent of obj-llvm)."""
    if pcfg:
        pd = pcfg.get("pgm_dir", "")
        if pd:
            p = Path(pd).resolve()
            parts = list(p.parts)
            if "obj-llvm" in parts:
                return Path(*parts[:parts.index("obj-llvm")])
            return p.parent
    return None


def _build_all_files_pool(base_dir: Path) -> List[str]:
    """Recursively collect all regular files under base_dir."""
    pool: List[str] = []
    if not base_dir or not base_dir.exists():
        return pool
    try:
        for p in base_dir.rglob("*"):
            try:
                if p.is_file():
                    pool.append(str(p.resolve()))
            except Exception:
                continue
    except Exception:
        return pool
    return pool


# ----------------------- option: --help parsing (from featmaker) -----------------------
_RE_LONG = re.compile(r"--[A-Za-z0-9][A-Za-z0-9\-]*")
_RE_SHORT = re.compile(r"(?<!-)-[A-Za-z]\b")


def _extract_all_flags_from_help(help_text: str) -> List[str]:
    """Extract options from --help text."""
    found: Set[str] = set()
    for ln in help_text.splitlines():
        if "-" not in ln:
            continue
        for m in _RE_LONG.finditer(ln):
            found.add(m.group(0).rstrip(",.;:)=]"))
        for m in _RE_SHORT.finditer(ln):
            found.add(m.group(0).rstrip(",.;:)=]"))
    return sorted(found, key=lambda x: (0 if x.startswith("--") else 1, x))


def _locate_program_binary(prog, pcfg=None):
    """Locate the program binary via pgm-config gcov_path (+ exec_dir), then PATH."""
    candidates = []
    if pcfg:
        gp = pcfg.get("gcov_path", ""); ed = pcfg.get("exec_dir", "").strip("/")
        if gp:
            if ed: candidates.append(os.path.join(gp, ed, prog))
            candidates += [os.path.join(gp, "src", prog), os.path.join(gp, prog)]
    try:
        which = shutil.which(prog)
        if which:
            candidates.append(which)
    except Exception:
        pass
    for c in candidates:
        if c and os.path.isfile(c) and os.access(c, os.X_OK):
            return c
    return None


def _get_help_flag_candidates(prog) -> List[str]:
    """Run <prog> --help and return the list of available option candidates."""
    bin_path = _locate_program_binary(prog, pcfg)
    if not bin_path:
        return []
    try:
        res = sp.run([bin_path, "--help"], stdout=sp.PIPE, stderr=sp.STDOUT,
                     text=True, check=False, timeout=10)
        txt = res.stdout or ""
        return _extract_all_flags_from_help(txt)
    except Exception:
        return []


def _pick_one_random_flag(candidates: List[str]) -> str:
    """Pick one candidate at random; empty string if none."""
    if not candidates:
        return ""
    return random.choice(candidates)


# ----------------------- command builder (from featmaker style) -----------------------
def build_run_args(prog, option_flag, regex, src_file, src_file_2=None):
    """
    Assemble option + regex + src_file per program and return as a string.

    Rules:
    - option: a single randomly chosen flag (may be empty)
    - regex: generated via regexgen
    - src_file: a randomly chosen file path (fixed at program start)
    - diff uses two src_files
    - sed, gawk, csplit use the /regex/ form

    Assembly order: option regex src_file
    """
    q = _escape_sq((regex or "").strip())
    opt = option_flag.strip() if option_flag else ""
    opt_prefix = (opt + " ") if opt else ""

    sf1 = shlex.quote(src_file) if src_file else ""

    # --- per-program assembly ---
    # no hardcoded options; only options randomly chosen from --help are used.
    # only the regex-passing form differs per program.

    if prog == "m4":
        # m4: fixed --warn-macro-sequence invocation (no options, regex only; BRE)
        return f"--warn-macro-sequence='{q}' {sf1}".strip()

    if prog == "diff":
        # diff: option 'regex' src1 src2
        sf2 = shlex.quote(src_file_2) if src_file_2 else sf1
        return f"{opt_prefix}'{q}' {sf1} {sf2}".strip()

    elif prog in ("sed", "gawk", "csplit"):
        # use the /regex/ form
        return f"{opt_prefix}'/{q}/' {sf1}".strip()

    else:
        # everything else: option 'regex' src_file
        return f"{opt_prefix}'{q}' {sf1}".strip()


# ----------------------- argument parsing -----------------------
argv = sys.argv[1:]
parser = argparse.ArgumentParser()
required = parser.add_argument_group('required arguments')
required.add_argument('-t', '--time-budget', default=86400, type=int, metavar='INT',
                      help='Total time budget (sec).')
required.add_argument('-p', '--program', required=True, type=str, metavar='STR',
                      help='Name of program to replay.')

parser.add_argument('--small-budget', default=120, type=int, metavar='INT',
                    help='Per-sub-iteration time in seconds (default: 120)')

parser.add_argument('--regex-mode', type=str, default=None, choices=['bre','ere','pcre'],
                                        help='regex mode (per-program default if unspecified)')

parser.add_argument('--pgm-config', type=str, default=None,
                    help='pgm_config JSON (defaults to shared CompoSE/pgm_config/<prog>100.json)')
args = parser.parse_args(argv)

budget = args.time_budget
prog = args.program
small_budget = args.small_budget
cli_regex_mode = args.regex_mode

# ----------------------- pgm-config load + LLVM bitcode -----------------------
pcfg = None
_pgm_cfg_path = getattr(args, "pgm_config", None)
if not _pgm_cfg_path:
    _cr = compose_root()
    if _cr:
        _cand = _cr / "pgm_config" / f"{prog}100.json"
        if _cand.exists(): _pgm_cfg_path = str(_cand)
if _pgm_cfg_path and Path(_pgm_cfg_path).exists():
    try:
        pcfg = json.loads(Path(_pgm_cfg_path).read_text(encoding="utf-8"))
        if "pgm" not in pcfg and "pgm_name" in pcfg: pcfg["pgm"] = pcfg["pgm_name"]
        for k in ("pgm","pgm_dir","gcov_path","exec_dir","src_file","sym_args"): pcfg.setdefault(k, "")
        ROOT = str(compose_root() or Path.cwd())
        for k in ("pgm_dir","gcov_path"):
            v = pcfg.get(k, "")
            if v and not os.path.isabs(v):
                for base in [ROOT, os.getcwd(), str(Path(_pgm_cfg_path).parent.parent), str(Path(_pgm_cfg_path).parent)]:
                    c = os.path.join(base, v)
                    if os.path.exists(c): pcfg[k] = c; break
        print(f"[pgm-config] loaded: pgm={pcfg['pgm']}, pgm_dir={pcfg.get('pgm_dir','')}")
    except Exception as e:
        print(f"[pgm-config] parse failed: {e}"); pcfg = None

# LLVM bitcode (.bc) for KLEE: from pgm-config (pgm_dir + exec_dir + <prog>.bc)
llvm_path = ""
if pcfg and pcfg.get("pgm_dir"):
    _ed = pcfg.get("exec_dir", "").strip("/")
    llvm_path = os.path.join(pcfg["pgm_dir"], _ed, f"{prog}.bc") if _ed else os.path.join(pcfg["pgm_dir"], f"{prog}.bc")
if not llvm_path or not os.path.isfile(llvm_path):
    print(f"[ERROR] LLVM bitcode not found: {llvm_path or '(no pgm_dir in pgm-config)'}"); sys.exit(1)

x = input("Trial?")
_exp_root = os.environ.get("AAQC_EXP_ROOT") or str(Path(__file__).resolve().parent / "experiments")
test_path = f"{_exp_root}/Aaqc{test_dir[prog]}_depth_{x}"
os.makedirs(test_path, exist_ok=True)

# ----------------------- build src_file pool & fixed selection -----------------------
src_base_dir = _derive_src_base_dir(prog, pcfg)
src_pool: List[str] = []
if src_base_dir:
    print(f"[src_file] base dir: {src_base_dir}")
    src_pool = _build_all_files_pool(src_base_dir)
    print(f"[src_file] pooled files: {len(src_pool)}")
else:
    print("[src_file] WARNING: cannot derive base dir; src_file will be empty.")

# pick one src_file to fix for the whole run
if src_pool:
    fixed_src_file = random.choice(src_pool)
else:
    fixed_src_file = ""
    print("[src_file] WARNING: src_pool empty -> src_file will be empty.")

if fixed_src_file:
    print(f"[src_file] FIXED for entire run: {fixed_src_file}")

# diff also needs a second src_file
fixed_src_file_2: Optional[str] = None
if prog in _DUAL_SRC_PROGRAMS:
    if src_pool:
        pool2 = [f for f in src_pool if f != fixed_src_file]
        fixed_src_file_2 = random.choice(pool2) if pool2 else fixed_src_file
    else:
        fixed_src_file_2 = fixed_src_file
    print(f"[src_file] FIXED src_file_2 for {prog}: {fixed_src_file_2}")

# ----------------------- pre-collect option candidates -----------------------
option_candidates = _get_help_flag_candidates(prog)
if option_candidates:
    print(f"[option] found {len(option_candidates)} candidates from --help (sample: {option_candidates[:5]})")
else:
    print(f"[option] no candidates found from --help; will use no extra flags.")

# ----------------------- original aaqc logic (4 iterations round-robin) -----------------------
prev_outdirs = [None, None, None, None]
j_counts = [0, 0, 0, 0]


# ── KLEE binaries live inside this tool directory (CompoSE_Aaqc/src/...) ──
_AAQC_ROOT = Path(__file__).resolve().parent
_VANILLA_KLEE = str(_AAQC_ROOT / "src" / "valina-build" / "bin" / "klee")
_QC_KLEE = str(_AAQC_ROOT / "src" / "qc-build" / "bin" / "klee")

def build_base_cmd(i):
    cache_flag = "-use-node-cache-stp -use-global-id"
    if i == 0:
        return f"{_VANILLA_KLEE} {flags.get(prog, '')} -use-cex-cache -use-branch-cache"
    elif i == 1:
        return f"{_QC_KLEE} {flags.get(prog, '')} -use-cex-cache -use-branch-cache=false -use-iso-cache {cache_flag}"
    elif i == 2:
        return f"{_QC_KLEE} {flags.get(prog, '')} -use-rebase -use-recursive-rebase -reuse-segments -use-cex-cache=false -use-branch-cache {cache_flag}"
    else:
        return f"{_QC_KLEE} {flags.get(prog, '')} -use-rebase -use-recursive-rebase -use-cex-cache=false -use-branch-cache=false -use-iso-cache {cache_flag}"

def extra_flags(i, j):
    if (j % 3) == 0:
        return "-search=random-path -search=nurs:covnew"
    elif (j % 3) == 1:
        return "-search=dfs"
    else:
        return "-search=nurs:md2u"

# prepare experiment directory
for i in range(4):
    os.makedirs(f"{test_path}/iteration-{i}", exist_ok=True)

total_remaining = budget
print(f"[Round-Robin Mode] total_budget={total_remaining}s, small_budget={small_budget}s")

# Naive seed cache for random seed reuse
seed_cache = NaiveSeedCache(Path(test_path) / "seed_cache")

# round-robin: 0->1->2->3->0->1->... until budget is exhausted
while total_remaining > 0:
    for i in range(4):
        if total_remaining <= 0:
            break

        j = j_counts[i]
        sub_time = min(small_budget, total_remaining)
        outdir = f"{test_path}/iteration-{i}/{j}"
        other_settings = (
            f"-libc=uclibc -posix-runtime -external-calls=all "
            f"-only-output-states-covering-new -output-dir={outdir} -max-time={sub_time}"
        )

        base_cmd = build_base_cmd(i)

        # seed setup: AAQC default seed (prev_outdir) + NaiveSeedCache random seed
        seed_flags = ""
        prev_sd = prev_outdirs[i]  # AAQC default: previous result of the same build
        rand_sd = seed_cache.get_random_seed_dir()  # random seed

        if prev_sd or rand_sd:
            if prev_sd and rand_sd:
                # merge if both present
                merge_dir = str(Path(test_path) / f"merged_seeds_i{i}_j{j}")
                os.makedirs(merge_dir, exist_ok=True)
                try:
                    for kt in Path(prev_sd).glob("*.ktest"):
                        dst = Path(merge_dir) / kt.name
                        if not dst.exists(): shutil.copy2(str(kt), str(dst))
                except Exception: pass
                try:
                    for kt in Path(rand_sd).glob("*.ktest"):
                        dst = Path(merge_dir) / f"sc_{kt.name}"
                        if not dst.exists(): shutil.copy2(str(kt), str(dst))
                except Exception: pass
                seed_flags = f"--seed-dir={merge_dir} --allow-seed-extension"
            elif prev_sd:
                seed_flags = f"--seed-dir={prev_sd} --allow-seed-extension"
            elif rand_sd:
                seed_flags = f"--seed-dir={rand_sd} --allow-seed-extension"

        # extra options per sub-iteration
        xflags = extra_flags(i, j)

        # build symbolic args / flags
        sym_cmd = sym_commands.get(
            prog,
            "-sym-args 0 1 10 -sym-args 0 2 2 -sym-files 1 8 -sym-stdin 8 -sym-stdout"
        )

        # determine regex mode
        this_mode = get_mode_for_prog(prog, cli_regex_mode)

        # right before each run: generate one regex via regexgen
        rgx = generate_regex_with_regexgen(this_mode)

        # right before each run: pick one random option
        rand_option = _pick_one_random_flag(option_candidates)

        # assemble option + regex + src_file per program
        run_args = build_run_args(
            prog, rand_option, rgx,
            fixed_src_file,
            src_file_2=fixed_src_file_2
        )

        # final command: klee + flags -> .bc -> (option+regex+src_file) -> symbolic args
        if run_args:
            cmd = f"{base_cmd} {seed_flags} {xflags} {other_settings} {llvm_path} {run_args} {sym_cmd}"
        else:
            cmd = f"{base_cmd} {seed_flags} {xflags} {other_settings} {llvm_path} {sym_cmd}"

        print(f"  Running Iteration {i}-{j} for {sub_time}s")
        print(f"  [regexgen mode={this_mode}] regex={rgx}")
        print(f"  [option] {rand_option if rand_option else '(none)'}")
        print(f"  [src_file] {fixed_src_file}")
        if prog in _DUAL_SRC_PROGRAMS:
            print(f"  [src_file_2] {fixed_src_file_2}")
        print(cmd)
        _t0 = time.monotonic()
        os.system(cmd)
        _elapsed = time.monotonic() - _t0

        # Store seeds from this execution
        seed_cache.store(i, j, outdir)

        # update state
        prev_outdirs[i] = outdir
        j_counts[i] += 1
        total_remaining -= max(_elapsed, 1)